name: Reusable OpenAPI Lint

on:
  workflow_call:
    inputs:
      spec_path:
        description: "Путь к openapi.yaml (относительно корня)"
        required: true
        type: string

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo (с openapi.yaml)
        uses: actions/checkout@v3

      - name: Checkout reusable workflow repo
        uses: actions/checkout@v3
        with:
          repository: eugenezorkin/openapi-ci-checks
          path: checks

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: checks
        run: npm install

      - name: Spectral lint
        run: npx --prefix checks spectral lint --ruleset=checks/.spectral.yaml ${{ inputs.spec_path }}

      - name: Swagger CLI validate
        run: npx --prefix checks swagger-cli validate ${{ inputs.spec_path }}
